### ISSUE TITLE
Problem of vector initializing 

### ISSUE THREAD

**Issue by zoncpp** [misoboute/playground#1]
Hi,
In [/playground/tree/master/areas/challenge/cafe-bazaar-2](url)
On the line 47, **buffer_ definition** , Shouldn't this be defined so : `std::vector<T> buffer_{ std::vector<T>(S) }` ?
Because I had buffer_ just with size 2 !

**Comment by misoboute** [comment]
> Hi,
> In [/playground/tree/master/areas/challenge/cafe-bazaar-2](url)
> On the line 47, **buffer_ definition** , Shouldn't this be defined so : `std::vector<T> buffer_{ std::vector<T>(S) }` ?
> Because I had buffer_ just with size 2 !

[cafe-bazaar-2/main.cpp#L47](https://github.com/misoboute/playground/blob/2395109255af618f737e68eed894aea229dc3096/areas/challenge/cafe-bazaar-2/main.cpp#L47) defines the vector and initializes it to have `S` elements of type `T` and initializes all the elements using the default constructor `T()`. As you suggest, since the default constructor for `T()` is intended, the second argument can be omitted and the `std::vector` constructor will take care of it. I have just included the second arg for the sake of clarity. However, you don't also need to initialize the vector and then move it into `buffer_`. So you can also define it as:
```C++
    std::vector<T> buffer_ { S };
```
